#common configuration shared between all applications
configserver:
    name: Docker JHipster Registry
    status: Connected to the JHipster Registry running in Docker

jhipster:
    security:
        authentication:
            jwt:
                secret: 7f6054d684e5b4655f53589dd2157d46f40d8fcf
    logging:
        logstash: # forward logs to ELK
            enabled: true
            host: jhipster-logstash
    metrics:
        logs: # report metrics in the logs
            enabled: true
            report-frequency: 60 # in seconds
spring:
    zipkin:
        base-url: http://jhipster-zipkin:9411
        enabled: true

eureka:
    client:
        service-url:
            defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
